package got.common.entity;

import got.common.entity.animal.*;
import got.common.entity.dragon.GOTEntityDragon;
import got.common.entity.essos.*;
import got.common.entity.essos.gold.*;
import got.common.entity.essos.legendary.quest.*;
import got.common.entity.essos.mossovy.*;
import got.common.entity.other.*;
import got.common.entity.westeros.*;
import got.common.entity.westeros.arryn.*;
import got.common.entity.westeros.crownlands.*;
import got.common.entity.westeros.dorne.*;
import got.common.entity.westeros.dragonstone.*;
import got.common.entity.westeros.gift.*;
import got.common.entity.westeros.hillmen.*;
import got.common.entity.westeros.ice.*;
import got.common.entity.westeros.ironborn.*;
import got.common.entity.westeros.north.*;
import got.common.entity.westeros.north.hillmen.*;
import got.common.entity.westeros.reach.*;
import got.common.entity.westeros.riverlands.*;
import got.common.entity.westeros.stormlands.*;
import got.common.entity.westeros.westerlands.*;
import got.common.entity.westeros.wildling.*;
import got.common.entity.westeros.wildling.thenn.*;
import got.common.faction.GOTFaction;

public class GOTEntity {
	public static int id;

	public static void preInit() {
		GOTEntityRegistry.register(GOTEntityBison.class, id++, 7488812);
		GOTEntityRegistry.register(GOTEntityBear.class, id++, 7492416);
		GOTEntityRegistry.register(GOTEntityBird.class, id++, 7451872);
		GOTEntityRegistry.register(GOTEntityButterfly.class, id++, 16119285);
		GOTEntityRegistry.register(GOTEntityCamel.class, id++, 13150061);
		GOTEntityRegistry.register(GOTEntityCrocodile.class, id++, 2896659);
		GOTEntityRegistry.register(GOTEntityDeer.class, id++, 5978669);
		GOTEntityRegistry.register(GOTEntityDesertScorpion.class, id++, 16376764);
		GOTEntityRegistry.register(GOTEntityDikDik.class, id++, 12023867);
		GOTEntityRegistry.register(GOTEntityDirewolf.class, id++, 0x808080);
		GOTEntityRegistry.register(GOTEntityDragon.class, id++, 0x282728);
		GOTEntityRegistry.register(GOTEntityElephant.class, id++, 9605778);
		GOTEntityRegistry.register(GOTEntityFish.class, id++, 7053203);
		GOTEntityRegistry.register(GOTEntityFlamingo.class, id++, 16087966);
		GOTEntityRegistry.register(GOTEntityGemsbok.class, id++, 11759423);
		GOTEntityRegistry.register(GOTEntityGiraffe.class, id++, 13608551);
		GOTEntityRegistry.register(GOTEntityGorcrow.class, id++, 928034);
		GOTEntityRegistry.register(GOTEntityHorse.class, id++, 8601889);
		GOTEntityRegistry.register(GOTEntityJungleScorpion.class, id++, 2630945);
		GOTEntityRegistry.register(GOTEntityWhiteBison.class, id++, 16702665);
		GOTEntityRegistry.register(GOTEntityLion.class, id++, 13345354);
		GOTEntityRegistry.register(GOTEntityLioness.class, id++, 13346908);
		GOTEntityRegistry.register(GOTEntityMammoth.class, id++, 5653040);
		GOTEntityRegistry.register(GOTEntityManticore.class, id++, 0x2B3F19);
		GOTEntityRegistry.register(GOTEntityMidges.class, id++, 5653040);
		GOTEntityRegistry.register(GOTEntityRabbit.class, id++, 9860178);
		GOTEntityRegistry.register(GOTEntityRedScorpion.class, id++, 0x7c0a02);
		GOTEntityRegistry.register(GOTEntityRhino.class, id++, 6118481);
		GOTEntityRegistry.register(GOTEntitySeagull.class, id++, 15920107);
		GOTEntityRegistry.register(GOTEntityShadowcat.class, id++, 0x282728);
		GOTEntityRegistry.register(GOTEntitySnowBear.class, id++, 15594495);
		GOTEntityRegistry.register(GOTEntitySwan.class, id++, 16119285);
		GOTEntityRegistry.register(GOTEntityTermite.class, id++, 0x282728);
		GOTEntityRegistry.register(GOTEntityWalrus.class, id++, 7053203);
		GOTEntityRegistry.register(GOTEntityWhiteOryx.class, id++, 16381146);
		GOTEntityRegistry.register(GOTEntityBoar.class, id++, 6635562);
		GOTEntityRegistry.register(GOTEntityWoolyRhino.class, id++, 5653040);
		GOTEntityRegistry.register(GOTEntityWyvern.class, id++, 2896659);
		GOTEntityRegistry.register(GOTEntityZebra.class, id++, 15000804);
		GOTEntityRegistry.register(GOTEntityShryke.class, id++, 2896659);

		GOTEntityRegistry.register(GOTEntityWesterosBandit.class, id++, 0xBABABA);
		GOTEntityRegistry.register(GOTEntityWesterosThief.class, id++, 0xBABABA);
		GOTEntityRegistry.register(GOTEntityWesterosScrapTrader.class, id++, 0xBABABA);
		GOTEntityRegistry.register(GOTEntityEssosBandit.class, id++, 13345354);
		GOTEntityRegistry.register(GOTEntityEssosThief.class, id++, 13345354);
		GOTEntityRegistry.register(GOTEntityEssosScrapTrader.class, id++, 13345354);

		GOTEntityRegistry.register(GOTEntityProstitute.class, id++, 16087966);
		GOTEntityRegistry.register(GOTEntityMaester.class, id++, 0xffffff);
		GOTEntityRegistry.register(GOTEntitySepton.class, id++, 0xffd700);
		GOTEntityRegistry.register(GOTEntityRedPriest.class, id++, 0x7c0a02);
		GOTEntityRegistry.register(GOTEntityIronbornPriest.class, id++, GOTFaction.IRONBORN);
		GOTEntityRegistry.register(GOTEntityBarrowWight.class, id++, 2896659);
		GOTEntityRegistry.register(GOTEntityMarshWraith.class, id++, 10524036);
		GOTEntityRegistry.register(GOTEntityStoneMan.class, id++, 0xBABABA);
		GOTEntityRegistry.register(GOTEntityMercenary.class, id++, 0xBABABA);

		GOTEntityRegistry.register(GOTEntityWhiteWalker.class, id++, GOTFaction.WHITE_WALKER);
		GOTEntityRegistry.register(GOTEntityWight.class, id++, GOTFaction.WHITE_WALKER);
		GOTEntityRegistry.register(GOTEntityIceSpider.class, id++, GOTFaction.WHITE_WALKER);
		GOTEntityRegistry.register(GOTEntityWightGiant.class, id++, GOTFaction.WHITE_WALKER);

		GOTEntityRegistry.register(GOTEntityWildling.class, id++, GOTFaction.WILDLING);
		GOTEntityRegistry.register(GOTEntityWildlingArcher.class, id++, GOTFaction.WILDLING);
		GOTEntityRegistry.register(GOTEntityWildlingAxeThrower.class, id++, GOTFaction.WILDLING);
		GOTEntityRegistry.register(GOTEntityWildlingBannerBearer.class, id++, GOTFaction.WILDLING);
		GOTEntityRegistry.register(GOTEntityWildlingChieftain.class, id++, GOTFaction.WILDLING);
		GOTEntityRegistry.register(GOTEntityGiant.class, id++, GOTFaction.WILDLING);

		GOTEntityRegistry.register(GOTEntityThenn.class, id++, GOTFaction.WILDLING);
		GOTEntityRegistry.register(GOTEntityThennArcher.class, id++, GOTFaction.WILDLING);
		GOTEntityRegistry.register(GOTEntityThennAxeThrower.class, id++, GOTFaction.WILDLING);
		GOTEntityRegistry.register(GOTEntityThennBannerBearer.class, id++, GOTFaction.WILDLING);
		GOTEntityRegistry.register(GOTEntityThennBerserker.class, id++, GOTFaction.WILDLING);
		GOTEntityRegistry.register(GOTEntityThennMagnar.class, id++, GOTFaction.WILDLING);
		GOTEntityRegistry.register(GOTEntityThennBlacksmith.class, id++, GOTFaction.WILDLING);


		GOTEntityRegistry.register(GOTEntityGiftMan.class, id++, GOTFaction.NIGHT_WATCH);
		GOTEntityRegistry.register(GOTEntityGiftBlacksmith.class, id++, GOTFaction.NIGHT_WATCH);
		GOTEntityRegistry.register(GOTEntityGiftGuard.class, id++, GOTFaction.NIGHT_WATCH);
		GOTEntityRegistry.register(GOTEntityGiftBannerBearer.class, id++, GOTFaction.NIGHT_WATCH);

		GOTEntityRegistry.register(GOTEntityNorthMan.class, id++, GOTFaction.NORTH);
		GOTEntityRegistry.register(GOTEntityNorthLevyman.class, id++, GOTFaction.NORTH);
		GOTEntityRegistry.register(GOTEntityNorthLevymanArcher.class, id++, GOTFaction.NORTH);
		GOTEntityRegistry.register(GOTEntityNorthSoldier.class, id++, GOTFaction.NORTH);
		GOTEntityRegistry.register(GOTEntityNorthSoldierArcher.class, id++, GOTFaction.NORTH);
		GOTEntityRegistry.register(GOTEntityNorthGuard.class, id++, GOTFaction.NORTH);
		GOTEntityRegistry.register(GOTEntityNorthBannerBearer.class, id++, GOTFaction.NORTH);
		GOTEntityRegistry.register(GOTEntityNorthCaptain.class, id++, GOTFaction.NORTH);
		GOTEntityRegistry.register(GOTEntityNorthBlacksmith.class, id++, GOTFaction.NORTH);
		GOTEntityRegistry.register(GOTEntityNorthGoldsmith.class, id++, GOTFaction.NORTH);
		GOTEntityRegistry.register(GOTEntityNorthFarmer.class, id++, GOTFaction.NORTH);
		GOTEntityRegistry.register(GOTEntityNorthFarmhand.class, id++, GOTFaction.NORTH);
		GOTEntityRegistry.register(GOTEntityNorthBartender.class, id++, GOTFaction.NORTH);
		GOTEntityRegistry.register(GOTEntityNorthMiner.class, id++, GOTFaction.NORTH);
		GOTEntityRegistry.register(GOTEntityNorthLumberman.class, id++, GOTFaction.NORTH);
		GOTEntityRegistry.register(GOTEntityNorthMason.class, id++, GOTFaction.NORTH);
		GOTEntityRegistry.register(GOTEntityNorthBrewer.class, id++, GOTFaction.NORTH);
		GOTEntityRegistry.register(GOTEntityNorthFlorist.class, id++, GOTFaction.NORTH);
		GOTEntityRegistry.register(GOTEntityNorthButcher.class, id++, GOTFaction.NORTH);
		GOTEntityRegistry.register(GOTEntityNorthFishmonger.class, id++, GOTFaction.NORTH);
		GOTEntityRegistry.register(GOTEntityNorthBaker.class, id++, GOTFaction.NORTH);

		GOTEntityRegistry.register(GOTEntityNorthHillman.class, id++, GOTFaction.NORTH);
		GOTEntityRegistry.register(GOTEntityNorthHillmanWarrior.class, id++, GOTFaction.NORTH);
		GOTEntityRegistry.register(GOTEntityNorthHillmanCannibal.class, id++, GOTFaction.NORTH);
		GOTEntityRegistry.register(GOTEntityNorthHillmanMercenary.class, id++, GOTFaction.NORTH);
		GOTEntityRegistry.register(GOTEntityNorthHillmanArcher.class, id++, GOTFaction.NORTH);
		GOTEntityRegistry.register(GOTEntityNorthHillmanAxeThrower.class, id++, GOTFaction.NORTH);
		GOTEntityRegistry.register(GOTEntityNorthHillmanBannerBearer.class, id++, GOTFaction.NORTH);
		GOTEntityRegistry.register(GOTEntityNorthHillmanChieftain.class, id++, GOTFaction.NORTH);

		GOTEntityRegistry.register(GOTEntityIronbornMan.class, id++, GOTFaction.IRONBORN);
		GOTEntityRegistry.register(GOTEntityIronbornLevyman.class, id++, GOTFaction.IRONBORN);
		GOTEntityRegistry.register(GOTEntityIronbornLevymanArcher.class, id++, GOTFaction.IRONBORN);
		GOTEntityRegistry.register(GOTEntityIronbornSoldier.class, id++, GOTFaction.IRONBORN);
		GOTEntityRegistry.register(GOTEntityIronbornSoldierArcher.class, id++, GOTFaction.IRONBORN);
		GOTEntityRegistry.register(GOTEntityIronbornBannerBearer.class, id++, GOTFaction.IRONBORN);
		GOTEntityRegistry.register(GOTEntityIronbornCaptain.class, id++, GOTFaction.IRONBORN);
		GOTEntityRegistry.register(GOTEntityIronbornBaker.class, id++, GOTFaction.IRONBORN);
		GOTEntityRegistry.register(GOTEntityIronbornBartender.class, id++, GOTFaction.IRONBORN);
		GOTEntityRegistry.register(GOTEntityIronbornGoldsmith.class, id++, GOTFaction.IRONBORN);
		GOTEntityRegistry.register(GOTEntityIronbornBlacksmith.class, id++, GOTFaction.IRONBORN);
		GOTEntityRegistry.register(GOTEntityIronbornBrewer.class, id++, GOTFaction.IRONBORN);
		GOTEntityRegistry.register(GOTEntityIronbornButcher.class, id++, GOTFaction.IRONBORN);
		GOTEntityRegistry.register(GOTEntityIronbornFarmer.class, id++, GOTFaction.IRONBORN);
		GOTEntityRegistry.register(GOTEntityIronbornFarmhand.class, id++, GOTFaction.IRONBORN);
		GOTEntityRegistry.register(GOTEntityIronbornFishmonger.class, id++, GOTFaction.IRONBORN);
		GOTEntityRegistry.register(GOTEntityIronbornFlorist.class, id++, GOTFaction.IRONBORN);
		GOTEntityRegistry.register(GOTEntityIronbornMiner.class, id++, GOTFaction.IRONBORN);
		GOTEntityRegistry.register(GOTEntityIronbornLumberman.class, id++, GOTFaction.IRONBORN);
		GOTEntityRegistry.register(GOTEntityIronbornMason.class, id++, GOTFaction.IRONBORN);

		GOTEntityRegistry.register(GOTEntityWesterlandsMan.class, id++, GOTFaction.WESTERLANDS);
		GOTEntityRegistry.register(GOTEntityWesterlandsLevyman.class, id++, GOTFaction.WESTERLANDS);
		GOTEntityRegistry.register(GOTEntityWesterlandsLevymanArcher.class, id++, GOTFaction.WESTERLANDS);
		GOTEntityRegistry.register(GOTEntityWesterlandsSoldier.class, id++, GOTFaction.WESTERLANDS);
		GOTEntityRegistry.register(GOTEntityWesterlandsSoldierArcher.class, id++, GOTFaction.WESTERLANDS);
		GOTEntityRegistry.register(GOTEntityWesterlandsGuard.class, id++, GOTFaction.WESTERLANDS);
		GOTEntityRegistry.register(GOTEntityWesterlandsBannerBearer.class, id++, GOTFaction.WESTERLANDS);
		GOTEntityRegistry.register(GOTEntityWesterlandsCaptain.class, id++, GOTFaction.WESTERLANDS);
		GOTEntityRegistry.register(GOTEntityWesterlandsBaker.class, id++, GOTFaction.WESTERLANDS);
		GOTEntityRegistry.register(GOTEntityWesterlandsBartender.class, id++, GOTFaction.WESTERLANDS);
		GOTEntityRegistry.register(GOTEntityWesterlandsBlacksmith.class, id++, GOTFaction.WESTERLANDS);
		GOTEntityRegistry.register(GOTEntityWesterlandsGoldsmith.class, id++, GOTFaction.WESTERLANDS);
		GOTEntityRegistry.register(GOTEntityWesterlandsBrewer.class, id++, GOTFaction.WESTERLANDS);
		GOTEntityRegistry.register(GOTEntityWesterlandsButcher.class, id++, GOTFaction.WESTERLANDS);
		GOTEntityRegistry.register(GOTEntityWesterlandsFarmer.class, id++, GOTFaction.WESTERLANDS);
		GOTEntityRegistry.register(GOTEntityWesterlandsFarmhand.class, id++, GOTFaction.WESTERLANDS);
		GOTEntityRegistry.register(GOTEntityWesterlandsFishmonger.class, id++, GOTFaction.WESTERLANDS);
		GOTEntityRegistry.register(GOTEntityWesterlandsFlorist.class, id++, GOTFaction.WESTERLANDS);
		GOTEntityRegistry.register(GOTEntityWesterlandsMiner.class, id++, GOTFaction.WESTERLANDS);
		GOTEntityRegistry.register(GOTEntityWesterlandsLumberman.class, id++, GOTFaction.WESTERLANDS);
		GOTEntityRegistry.register(GOTEntityWesterlandsMason.class, id++, GOTFaction.WESTERLANDS);

		GOTEntityRegistry.register(GOTEntityRiverlandsMan.class, id++, GOTFaction.RIVERLANDS);
		GOTEntityRegistry.register(GOTEntityRiverlandsLevyman.class, id++, GOTFaction.RIVERLANDS);
		GOTEntityRegistry.register(GOTEntityRiverlandsLevymanArcher.class, id++, GOTFaction.RIVERLANDS);
		GOTEntityRegistry.register(GOTEntityRiverlandsSoldier.class, id++, GOTFaction.RIVERLANDS);
		GOTEntityRegistry.register(GOTEntityRiverlandsSoldierArcher.class, id++, GOTFaction.RIVERLANDS);
		GOTEntityRegistry.register(GOTEntityRiverlandsBannerBearer.class, id++, GOTFaction.RIVERLANDS);
		GOTEntityRegistry.register(GOTEntityRiverlandsCaptain.class, id++, GOTFaction.RIVERLANDS);
		GOTEntityRegistry.register(GOTEntityRiverlandsBaker.class, id++, GOTFaction.RIVERLANDS);
		GOTEntityRegistry.register(GOTEntityRiverlandsBartender.class, id++, GOTFaction.RIVERLANDS);
		GOTEntityRegistry.register(GOTEntityRiverlandsBlacksmith.class, id++, GOTFaction.RIVERLANDS);
		GOTEntityRegistry.register(GOTEntityRiverlandsGoldsmith.class, id++, GOTFaction.RIVERLANDS);
		GOTEntityRegistry.register(GOTEntityRiverlandsBrewer.class, id++, GOTFaction.RIVERLANDS);
		GOTEntityRegistry.register(GOTEntityRiverlandsButcher.class, id++, GOTFaction.RIVERLANDS);
		GOTEntityRegistry.register(GOTEntityRiverlandsFarmer.class, id++, GOTFaction.RIVERLANDS);
		GOTEntityRegistry.register(GOTEntityRiverlandsFarmhand.class, id++, GOTFaction.RIVERLANDS);
		GOTEntityRegistry.register(GOTEntityRiverlandsFishmonger.class, id++, GOTFaction.RIVERLANDS);
		GOTEntityRegistry.register(GOTEntityRiverlandsFlorist.class, id++, GOTFaction.RIVERLANDS);
		GOTEntityRegistry.register(GOTEntityRiverlandsMiner.class, id++, GOTFaction.RIVERLANDS);
		GOTEntityRegistry.register(GOTEntityRiverlandsLumberman.class, id++, GOTFaction.RIVERLANDS);
		GOTEntityRegistry.register(GOTEntityRiverlandsMason.class, id++, GOTFaction.RIVERLANDS);

		GOTEntityRegistry.register(GOTEntityHillman.class, id++, GOTFaction.HILL_TRIBES);
		GOTEntityRegistry.register(GOTEntityHillmanWarrior.class, id++, GOTFaction.HILL_TRIBES);
		GOTEntityRegistry.register(GOTEntityHillmanArcher.class, id++, GOTFaction.HILL_TRIBES);
		GOTEntityRegistry.register(GOTEntityHillmanAxeThrower.class, id++, GOTFaction.HILL_TRIBES);
		GOTEntityRegistry.register(GOTEntityHillmanBerserker.class, id++, GOTFaction.HILL_TRIBES);
		GOTEntityRegistry.register(GOTEntityHillmanBannerBearer.class, id++, GOTFaction.HILL_TRIBES);
		GOTEntityRegistry.register(GOTEntityHillmanWarlord.class, id++, GOTFaction.HILL_TRIBES);
		GOTEntityRegistry.register(GOTEntityHillmanBartender.class, id++, GOTFaction.HILL_TRIBES);

		GOTEntityRegistry.register(GOTEntityArrynMan.class, id++, GOTFaction.ARRYN);
		GOTEntityRegistry.register(GOTEntityArrynLevyman.class, id++, GOTFaction.ARRYN);
		GOTEntityRegistry.register(GOTEntityArrynLevymanArcher.class, id++, GOTFaction.ARRYN);
		GOTEntityRegistry.register(GOTEntityArrynSoldier.class, id++, GOTFaction.ARRYN);
		GOTEntityRegistry.register(GOTEntityArrynSoldierArcher.class, id++, GOTFaction.ARRYN);
		GOTEntityRegistry.register(GOTEntityArrynGuard.class, id++, GOTFaction.ARRYN);
		GOTEntityRegistry.register(GOTEntityArrynBannerBearer.class, id++, GOTFaction.ARRYN);
		GOTEntityRegistry.register(GOTEntityArrynCaptain.class, id++, GOTFaction.ARRYN);
		GOTEntityRegistry.register(GOTEntityArrynBaker.class, id++, GOTFaction.ARRYN);
		GOTEntityRegistry.register(GOTEntityArrynBartender.class, id++, GOTFaction.ARRYN);
		GOTEntityRegistry.register(GOTEntityArrynBlacksmith.class, id++, GOTFaction.ARRYN);
		GOTEntityRegistry.register(GOTEntityArrynGoldsmith.class, id++, GOTFaction.ARRYN);
		GOTEntityRegistry.register(GOTEntityArrynBrewer.class, id++, GOTFaction.ARRYN);
		GOTEntityRegistry.register(GOTEntityArrynButcher.class, id++, GOTFaction.ARRYN);
		GOTEntityRegistry.register(GOTEntityArrynFarmer.class, id++, GOTFaction.ARRYN);
		GOTEntityRegistry.register(GOTEntityArrynFarmhand.class, id++, GOTFaction.ARRYN);
		GOTEntityRegistry.register(GOTEntityArrynFishmonger.class, id++, GOTFaction.ARRYN);
		GOTEntityRegistry.register(GOTEntityArrynFlorist.class, id++, GOTFaction.ARRYN);
		GOTEntityRegistry.register(GOTEntityArrynMiner.class, id++, GOTFaction.ARRYN);
		GOTEntityRegistry.register(GOTEntityArrynLumberman.class, id++, GOTFaction.ARRYN);
		GOTEntityRegistry.register(GOTEntityArrynMason.class, id++, GOTFaction.ARRYN);

		GOTEntityRegistry.register(GOTEntityDragonstoneMan.class, id++, GOTFaction.DRAGONSTONE);
		GOTEntityRegistry.register(GOTEntityDragonstoneLevyman.class, id++, GOTFaction.DRAGONSTONE);
		GOTEntityRegistry.register(GOTEntityDragonstoneLevymanArcher.class, id++, GOTFaction.DRAGONSTONE);
		GOTEntityRegistry.register(GOTEntityDragonstoneSoldier.class, id++, GOTFaction.DRAGONSTONE);
		GOTEntityRegistry.register(GOTEntityDragonstoneSoldierArcher.class, id++, GOTFaction.DRAGONSTONE);
		GOTEntityRegistry.register(GOTEntityDragonstoneBannerBearer.class, id++, GOTFaction.DRAGONSTONE);
		GOTEntityRegistry.register(GOTEntityDragonstoneCaptain.class, id++, GOTFaction.DRAGONSTONE);
		GOTEntityRegistry.register(GOTEntityDragonstoneBaker.class, id++, GOTFaction.DRAGONSTONE);
		GOTEntityRegistry.register(GOTEntityDragonstoneBartender.class, id++, GOTFaction.DRAGONSTONE);
		GOTEntityRegistry.register(GOTEntityDragonstoneBlacksmith.class, id++, GOTFaction.DRAGONSTONE);
		GOTEntityRegistry.register(GOTEntityDragonstoneGoldsmith.class, id++, GOTFaction.DRAGONSTONE);
		GOTEntityRegistry.register(GOTEntityDragonstoneBrewer.class, id++, GOTFaction.DRAGONSTONE);
		GOTEntityRegistry.register(GOTEntityDragonstoneButcher.class, id++, GOTFaction.DRAGONSTONE);
		GOTEntityRegistry.register(GOTEntityDragonstoneFarmer.class, id++, GOTFaction.DRAGONSTONE);
		GOTEntityRegistry.register(GOTEntityDragonstoneFarmhand.class, id++, GOTFaction.DRAGONSTONE);
		GOTEntityRegistry.register(GOTEntityDragonstoneFishmonger.class, id++, GOTFaction.DRAGONSTONE);
		GOTEntityRegistry.register(GOTEntityDragonstoneFlorist.class, id++, GOTFaction.DRAGONSTONE);
		GOTEntityRegistry.register(GOTEntityDragonstoneMiner.class, id++, GOTFaction.DRAGONSTONE);
		GOTEntityRegistry.register(GOTEntityDragonstoneLumberman.class, id++, GOTFaction.DRAGONSTONE);
		GOTEntityRegistry.register(GOTEntityDragonstoneMason.class, id++, GOTFaction.DRAGONSTONE);

		GOTEntityRegistry.register(GOTEntityCrownlandsMan.class, id++, GOTFaction.CROWNLANDS);
		GOTEntityRegistry.register(GOTEntityCrownlandsLevyman.class, id++, GOTFaction.CROWNLANDS);
		GOTEntityRegistry.register(GOTEntityCrownlandsLevymanArcher.class, id++, GOTFaction.CROWNLANDS);
		GOTEntityRegistry.register(GOTEntityCrownlandsGuard.class, id++, GOTFaction.CROWNLANDS);
		GOTEntityRegistry.register(GOTEntityCrownlandsBannerBearer.class, id++, GOTFaction.CROWNLANDS);
		GOTEntityRegistry.register(GOTEntityKingsguard.class, id++, GOTFaction.CROWNLANDS);
		GOTEntityRegistry.register(GOTEntityCrownlandsCaptain.class, id++, GOTFaction.CROWNLANDS);
		GOTEntityRegistry.register(GOTEntityCrownlandsBaker.class, id++, GOTFaction.CROWNLANDS);
		GOTEntityRegistry.register(GOTEntityCrownlandsBartender.class, id++, GOTFaction.CROWNLANDS);
		GOTEntityRegistry.register(GOTEntityCrownlandsBlacksmith.class, id++, GOTFaction.CROWNLANDS);
		GOTEntityRegistry.register(GOTEntityCrownlandsGoldsmith.class, id++, GOTFaction.CROWNLANDS);
		GOTEntityRegistry.register(GOTEntityCrownlandsBrewer.class, id++, GOTFaction.CROWNLANDS);
		GOTEntityRegistry.register(GOTEntityCrownlandsButcher.class, id++, GOTFaction.CROWNLANDS);
		GOTEntityRegistry.register(GOTEntityCrownlandsFarmer.class, id++, GOTFaction.CROWNLANDS);
		GOTEntityRegistry.register(GOTEntityCrownlandsFarmhand.class, id++, GOTFaction.CROWNLANDS);
		GOTEntityRegistry.register(GOTEntityCrownlandsFishmonger.class, id++, GOTFaction.CROWNLANDS);
		GOTEntityRegistry.register(GOTEntityCrownlandsFlorist.class, id++, GOTFaction.CROWNLANDS);
		GOTEntityRegistry.register(GOTEntityCrownlandsMiner.class, id++, GOTFaction.CROWNLANDS);
		GOTEntityRegistry.register(GOTEntityCrownlandsLumberman.class, id++, GOTFaction.CROWNLANDS);
		GOTEntityRegistry.register(GOTEntityCrownlandsMason.class, id++, GOTFaction.CROWNLANDS);
		GOTEntityRegistry.register(GOTEntityCrownlandsAlchemist.class, id++, GOTFaction.CROWNLANDS);

		GOTEntityRegistry.register(GOTEntityStormlandsMan.class, id++, GOTFaction.STORMLANDS);
		GOTEntityRegistry.register(GOTEntityStormlandsLevyman.class, id++, GOTFaction.STORMLANDS);
		GOTEntityRegistry.register(GOTEntityStormlandsLevymanArcher.class, id++, GOTFaction.STORMLANDS);
		GOTEntityRegistry.register(GOTEntityStormlandsSoldier.class, id++, GOTFaction.STORMLANDS);
		GOTEntityRegistry.register(GOTEntityStormlandsSoldierArcher.class, id++, GOTFaction.STORMLANDS);
		GOTEntityRegistry.register(GOTEntityStormlandsBannerBearer.class, id++, GOTFaction.STORMLANDS);
		GOTEntityRegistry.register(GOTEntityStormlandsCaptain.class, id++, GOTFaction.STORMLANDS);
		GOTEntityRegistry.register(GOTEntityStormlandsBaker.class, id++, GOTFaction.STORMLANDS);
		GOTEntityRegistry.register(GOTEntityStormlandsBartender.class, id++, GOTFaction.STORMLANDS);
		GOTEntityRegistry.register(GOTEntityStormlandsBlacksmith.class, id++, GOTFaction.STORMLANDS);
		GOTEntityRegistry.register(GOTEntityStormlandsGoldsmith.class, id++, GOTFaction.STORMLANDS);
		GOTEntityRegistry.register(GOTEntityStormlandsBrewer.class, id++, GOTFaction.STORMLANDS);
		GOTEntityRegistry.register(GOTEntityStormlandsButcher.class, id++, GOTFaction.STORMLANDS);
		GOTEntityRegistry.register(GOTEntityStormlandsFarmer.class, id++, GOTFaction.STORMLANDS);
		GOTEntityRegistry.register(GOTEntityStormlandsFarmhand.class, id++, GOTFaction.STORMLANDS);
		GOTEntityRegistry.register(GOTEntityStormlandsFishmonger.class, id++, GOTFaction.STORMLANDS);
		GOTEntityRegistry.register(GOTEntityStormlandsFlorist.class, id++, GOTFaction.STORMLANDS);
		GOTEntityRegistry.register(GOTEntityStormlandsMiner.class, id++, GOTFaction.STORMLANDS);
		GOTEntityRegistry.register(GOTEntityStormlandsLumberman.class, id++, GOTFaction.STORMLANDS);
		GOTEntityRegistry.register(GOTEntityStormlandsMason.class, id++, GOTFaction.STORMLANDS);

		GOTEntityRegistry.register(GOTEntityReachMan.class, id++, GOTFaction.REACH);
		GOTEntityRegistry.register(GOTEntityReachLevyman.class, id++, GOTFaction.REACH);
		GOTEntityRegistry.register(GOTEntityReachLevymanArcher.class, id++, GOTFaction.REACH);
		GOTEntityRegistry.register(GOTEntityReachSoldier.class, id++, GOTFaction.REACH);
		GOTEntityRegistry.register(GOTEntityReachSoldierArcher.class, id++, GOTFaction.REACH);
		GOTEntityRegistry.register(GOTEntityReachGuard.class, id++, GOTFaction.REACH);
		GOTEntityRegistry.register(GOTEntityReachBannerBearer.class, id++, GOTFaction.REACH);
		GOTEntityRegistry.register(GOTEntityReachCaptain.class, id++, GOTFaction.REACH);
		GOTEntityRegistry.register(GOTEntityReachBaker.class, id++, GOTFaction.REACH);
		GOTEntityRegistry.register(GOTEntityReachBartender.class, id++, GOTFaction.REACH);
		GOTEntityRegistry.register(GOTEntityReachBlacksmith.class, id++, GOTFaction.REACH);
		GOTEntityRegistry.register(GOTEntityReachGoldsmith.class, id++, GOTFaction.REACH);
		GOTEntityRegistry.register(GOTEntityReachBrewer.class, id++, GOTFaction.REACH);
		GOTEntityRegistry.register(GOTEntityReachButcher.class, id++, GOTFaction.REACH);
		GOTEntityRegistry.register(GOTEntityReachFarmer.class, id++, GOTFaction.REACH);
		GOTEntityRegistry.register(GOTEntityReachFarmhand.class, id++, GOTFaction.REACH);
		GOTEntityRegistry.register(GOTEntityReachFishmonger.class, id++, GOTFaction.REACH);
		GOTEntityRegistry.register(GOTEntityReachFlorist.class, id++, GOTFaction.REACH);
		GOTEntityRegistry.register(GOTEntityReachMiner.class, id++, GOTFaction.REACH);
		GOTEntityRegistry.register(GOTEntityReachLumberman.class, id++, GOTFaction.REACH);
		GOTEntityRegistry.register(GOTEntityReachMason.class, id++, GOTFaction.REACH);

		GOTEntityRegistry.register(GOTEntityDorneMan.class, id++, GOTFaction.DORNE);
		GOTEntityRegistry.register(GOTEntityDorneLevyman.class, id++, GOTFaction.DORNE);
		GOTEntityRegistry.register(GOTEntityDorneLevymanArcher.class, id++, GOTFaction.DORNE);
		GOTEntityRegistry.register(GOTEntityDorneSoldier.class, id++, GOTFaction.DORNE);
		GOTEntityRegistry.register(GOTEntityDorneSoldierArcher.class, id++, GOTFaction.DORNE);
		GOTEntityRegistry.register(GOTEntityDorneBannerBearer.class, id++, GOTFaction.DORNE);
		GOTEntityRegistry.register(GOTEntityDorneCaptain.class, id++, GOTFaction.DORNE);
		GOTEntityRegistry.register(GOTEntityDorneBaker.class, id++, GOTFaction.DORNE);
		GOTEntityRegistry.register(GOTEntityDorneBartender.class, id++, GOTFaction.DORNE);
		GOTEntityRegistry.register(GOTEntityDorneBlacksmith.class, id++, GOTFaction.DORNE);
		GOTEntityRegistry.register(GOTEntityDorneGoldsmith.class, id++, GOTFaction.DORNE);
		GOTEntityRegistry.register(GOTEntityDorneBrewer.class, id++, GOTFaction.DORNE);
		GOTEntityRegistry.register(GOTEntityDorneButcher.class, id++, GOTFaction.DORNE);
		GOTEntityRegistry.register(GOTEntityDorneFarmer.class, id++, GOTFaction.DORNE);
		GOTEntityRegistry.register(GOTEntityDorneFarmhand.class, id++, GOTFaction.DORNE);
		GOTEntityRegistry.register(GOTEntityDorneFishmonger.class, id++, GOTFaction.DORNE);
		GOTEntityRegistry.register(GOTEntityDorneFlorist.class, id++, GOTFaction.DORNE);
		GOTEntityRegistry.register(GOTEntityDorneMiner.class, id++, GOTFaction.DORNE);
		GOTEntityRegistry.register(GOTEntityDorneLumberman.class, id++, GOTFaction.DORNE);
		GOTEntityRegistry.register(GOTEntityDorneMason.class, id++, GOTFaction.DORNE);

		GOTEntityRegistry.register(GOTEntityGoldenWarrior.class, id++, 0xffd700);
		GOTEntityRegistry.register(GOTEntityGoldenSpearman.class, id++, 0xffd700);
		GOTEntityRegistry.register(GOTEntityGoldenBannerBearer.class, id++, 0xffd700);
		GOTEntityRegistry.register(GOTEntityGoldenCaptain.class, id++, 0xffd700);

		GOTEntityRegistry.register(GOTEntityUlthosSpider.class, id++, GOTFaction.HIGH_POWER);
		GOTEntityRegistry.register(GOTEntityBlizzard.class, id++, GOTFaction.WHITE_WALKER);

		GOTEntityRegistry.registerLegendaryNPC(GOTEntityJaqenHghar.class, id++, GOTFaction.HIGH_POWER);

		GOTEntityRegistry.registerHidden(GOTEntityPortal.class, id++, 80, 3, true);
		GOTEntityRegistry.registerHidden(GOTEntitySmokeRing.class, id++, 64, 10, true);
		GOTEntityRegistry.registerHidden(GOTEntityBomb.class, id++, 160, 10, true);
		GOTEntityRegistry.registerHidden(GOTEntitySpear.class, id++, 64, Integer.MAX_VALUE, false);
		GOTEntityRegistry.registerHidden(GOTEntityPlate.class, id++, 64, 3, true);
		GOTEntityRegistry.registerHidden(GOTEntityThrowingAxe.class, id++, 64, Integer.MAX_VALUE, false);
		GOTEntityRegistry.registerHidden(GOTEntityCrossbowBolt.class, id++, 64, Integer.MAX_VALUE, false);
		GOTEntityRegistry.registerHidden(GOTEntityPebble.class, id++, 64, 3, true);
		GOTEntityRegistry.registerHidden(GOTEntityMysteryWeb.class, id++, 64, 10, true);
		GOTEntityRegistry.registerHidden(GOTEntityTraderRespawn.class, id++, 80, 3, true);
		GOTEntityRegistry.registerHidden(GOTEntityThrownRock.class, id++, 64, 10, true);
		GOTEntityRegistry.registerHidden(GOTEntityBarrel.class, id++, 80, 3, true);
		GOTEntityRegistry.registerHidden(GOTEntityInvasionSpawner.class, id++, 80, 3, true);
		GOTEntityRegistry.registerHidden(GOTEntityThrownTermite.class, id++, 64, 10, true);
		GOTEntityRegistry.registerHidden(GOTEntityConker.class, id++, 64, 3, true);
		GOTEntityRegistry.registerHidden(GOTEntityFishHook.class, id++, 64, 5, true);
		GOTEntityRegistry.registerHidden(GOTEntityDart.class, id++, 64, Integer.MAX_VALUE, false);
		GOTEntityRegistry.registerHidden(GOTEntityNPCRespawner.class, id++, 80, 3, true);
		GOTEntityRegistry.registerHidden(GOTEntityFallingTreasure.class, id++, 160, 20, true);
		GOTEntityRegistry.registerHidden(GOTEntityFallingFireJar.class, id++, 160, 20, true);
		GOTEntityRegistry.registerHidden(GOTEntityFirePot.class, id++, 64, 3, true);
		GOTEntityRegistry.registerHidden(GOTEntityArrowPoisoned.class, id++, 64, 20, false);
		GOTEntityRegistry.registerHidden(GOTEntityArrowFire.class, id++, 64, 20, false);
		GOTEntityRegistry.registerHidden(GOTEntityLionRug.class, id++, 80, 3, true);
		GOTEntityRegistry.registerHidden(GOTEntityBearRug.class, id++, 80, 3, true);
		GOTEntityRegistry.registerHidden(GOTEntityGiraffeRug.class, id++, 80, 3, true);
		GOTEntityRegistry.registerHidden(GOTEntityBanner.class, id++, 160, 3, true);
		GOTEntityRegistry.registerHidden(GOTEntityBannerWall.class, id++, 160, Integer.MAX_VALUE, false);
		GOTEntityRegistry.registerHidden(GOTEntityLingeringPotion.class, id++, 64, 10, true);
		GOTEntityRegistry.registerHidden(GOTEntityLingeringEffect.class, id++, 64, 1, true);
		GOTEntityRegistry.registerHidden(GOTEntityCargocart.class, id++, 80, 20, false);
		GOTEntityRegistry.registerHidden(GOTEntityPlowcart.class, id++, 80, 20, false);
		GOTEntityRegistry.registerHidden(GOTEntityMarshWraithBall.class, id++, 64, 10, true);
		GOTEntityRegistry.registerHidden(GOTEntitySnowball.class, id++, 64, 1, true);

	}
}